---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: sfera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2.10.2-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: sfera
spec:
  ports:
    - port: 80
  selector:
    app: caddy
---
apiVersion:  traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: caddy
  namespace: sfera
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`caddy.sfera.ovh`)
      kind: Rule
      services:
        - name: caddy
          port: 80
